/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as RoadmapSharedWithMeRouteImport } from './routes/roadmap/shared-with-me'
import { Route as ProjectProjectIdRouteImport } from './routes/project/$projectId'
import { Route as ProfileProfileIdRouteImport } from './routes/profile/$profileId'
import { Route as ConsultantBrowseRouteImport } from './routes/consultant/browse'
import { Route as ConsultantApplyRouteImport } from './routes/consultant/apply'
import { Route as ConsultantProfileIdRouteImport } from './routes/consultant/$profileId'
import { Route as ClientProjectPostingRouteImport } from './routes/client/project-posting'
import { Route as AuthVerifyRouteImport } from './routes/auth/verify'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminMatchRouteImport } from './routes/admin/match'
import { Route as AdminApproveAdminRouteImport } from './routes/admin/approve-admin'
import { Route as AdminApplicationsRouteImport } from './routes/admin/applications'
import { Route as ProjectRoadmapIndexRouteImport } from './routes/project/roadmap/index'
import { Route as RoadmapSharedTokenRouteImport } from './routes/roadmap/shared/$token'
import { Route as ProjectProjectIdWorkItemsRouteImport } from './routes/project/$projectId/work-items'
import { Route as ProjectProjectIdTimeRouteImport } from './routes/project/$projectId/time'
import { Route as ProjectProjectIdRoadmapRouteImport } from './routes/project/$projectId/roadmap'
import { Route as ProjectProjectIdPaymentsRouteImport } from './routes/project/$projectId/payments'
import { Route as ProjectProjectIdOverviewRouteImport } from './routes/project/$projectId/overview'
import { Route as ProjectProjectIdFilesRouteImport } from './routes/project/$projectId/files'
import { Route as AuthAdminSigninRouteImport } from './routes/auth/admin/signin'
import { Route as AuthAdminLoginRouteImport } from './routes/auth/admin/login'
import { Route as ProjectProjectIdRoadmapRoadmapIdRouteImport } from './routes/project/$projectId/roadmap/$roadmapId'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const RoadmapSharedWithMeRoute = RoadmapSharedWithMeRouteImport.update({
  id: '/roadmap/shared-with-me',
  path: '/roadmap/shared-with-me',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectProjectIdRoute = ProjectProjectIdRouteImport.update({
  id: '/project/$projectId',
  path: '/project/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileProfileIdRoute = ProfileProfileIdRouteImport.update({
  id: '/profile/$profileId',
  path: '/profile/$profileId',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultantBrowseRoute = ConsultantBrowseRouteImport.update({
  id: '/consultant/browse',
  path: '/consultant/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultantApplyRoute = ConsultantApplyRouteImport.update({
  id: '/consultant/apply',
  path: '/consultant/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultantProfileIdRoute = ConsultantProfileIdRouteImport.update({
  id: '/consultant/$profileId',
  path: '/consultant/$profileId',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientProjectPostingRoute = ClientProjectPostingRouteImport.update({
  id: '/client/project-posting',
  path: '/client/project-posting',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/auth/verify',
  path: '/auth/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMatchRoute = AdminMatchRouteImport.update({
  id: '/match',
  path: '/match',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApproveAdminRoute = AdminApproveAdminRouteImport.update({
  id: '/approve-admin',
  path: '/approve-admin',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApplicationsRoute = AdminApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => AdminRoute,
} as any)
const ProjectRoadmapIndexRoute = ProjectRoadmapIndexRouteImport.update({
  id: '/project/roadmap/',
  path: '/project/roadmap/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapSharedTokenRoute = RoadmapSharedTokenRouteImport.update({
  id: '/roadmap/shared/$token',
  path: '/roadmap/shared/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectProjectIdWorkItemsRoute =
  ProjectProjectIdWorkItemsRouteImport.update({
    id: '/work-items',
    path: '/work-items',
    getParentRoute: () => ProjectProjectIdRoute,
  } as any)
const ProjectProjectIdTimeRoute = ProjectProjectIdTimeRouteImport.update({
  id: '/time',
  path: '/time',
  getParentRoute: () => ProjectProjectIdRoute,
} as any)
const ProjectProjectIdRoadmapRoute = ProjectProjectIdRoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => ProjectProjectIdRoute,
} as any)
const ProjectProjectIdPaymentsRoute =
  ProjectProjectIdPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => ProjectProjectIdRoute,
  } as any)
const ProjectProjectIdOverviewRoute =
  ProjectProjectIdOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => ProjectProjectIdRoute,
  } as any)
const ProjectProjectIdFilesRoute = ProjectProjectIdFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => ProjectProjectIdRoute,
} as any)
const AuthAdminSigninRoute = AuthAdminSigninRouteImport.update({
  id: '/auth/admin/signin',
  path: '/auth/admin/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAdminLoginRoute = AuthAdminLoginRouteImport.update({
  id: '/auth/admin/login',
  path: '/auth/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectProjectIdRoadmapRoadmapIdRoute =
  ProjectProjectIdRoadmapRoadmapIdRouteImport.update({
    id: '/$roadmapId',
    path: '/$roadmapId',
    getParentRoute: () => ProjectProjectIdRoadmapRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/landing': typeof LandingRoute
  '/onboarding': typeof OnboardingRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/approve-admin': typeof AdminApproveAdminRoute
  '/admin/match': typeof AdminMatchRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/client/project-posting': typeof ClientProjectPostingRoute
  '/consultant/$profileId': typeof ConsultantProfileIdRoute
  '/consultant/apply': typeof ConsultantApplyRoute
  '/consultant/browse': typeof ConsultantBrowseRoute
  '/profile/$profileId': typeof ProfileProfileIdRoute
  '/project/$projectId': typeof ProjectProjectIdRouteWithChildren
  '/roadmap/shared-with-me': typeof RoadmapSharedWithMeRoute
  '/admin/': typeof AdminIndexRoute
  '/auth/admin/login': typeof AuthAdminLoginRoute
  '/auth/admin/signin': typeof AuthAdminSigninRoute
  '/project/$projectId/files': typeof ProjectProjectIdFilesRoute
  '/project/$projectId/overview': typeof ProjectProjectIdOverviewRoute
  '/project/$projectId/payments': typeof ProjectProjectIdPaymentsRoute
  '/project/$projectId/roadmap': typeof ProjectProjectIdRoadmapRouteWithChildren
  '/project/$projectId/time': typeof ProjectProjectIdTimeRoute
  '/project/$projectId/work-items': typeof ProjectProjectIdWorkItemsRoute
  '/roadmap/shared/$token': typeof RoadmapSharedTokenRoute
  '/project/roadmap': typeof ProjectRoadmapIndexRoute
  '/project/$projectId/roadmap/$roadmapId': typeof ProjectProjectIdRoadmapRoadmapIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/landing': typeof LandingRoute
  '/onboarding': typeof OnboardingRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/approve-admin': typeof AdminApproveAdminRoute
  '/admin/match': typeof AdminMatchRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/client/project-posting': typeof ClientProjectPostingRoute
  '/consultant/$profileId': typeof ConsultantProfileIdRoute
  '/consultant/apply': typeof ConsultantApplyRoute
  '/consultant/browse': typeof ConsultantBrowseRoute
  '/profile/$profileId': typeof ProfileProfileIdRoute
  '/project/$projectId': typeof ProjectProjectIdRouteWithChildren
  '/roadmap/shared-with-me': typeof RoadmapSharedWithMeRoute
  '/admin': typeof AdminIndexRoute
  '/auth/admin/login': typeof AuthAdminLoginRoute
  '/auth/admin/signin': typeof AuthAdminSigninRoute
  '/project/$projectId/files': typeof ProjectProjectIdFilesRoute
  '/project/$projectId/overview': typeof ProjectProjectIdOverviewRoute
  '/project/$projectId/payments': typeof ProjectProjectIdPaymentsRoute
  '/project/$projectId/roadmap': typeof ProjectProjectIdRoadmapRouteWithChildren
  '/project/$projectId/time': typeof ProjectProjectIdTimeRoute
  '/project/$projectId/work-items': typeof ProjectProjectIdWorkItemsRoute
  '/roadmap/shared/$token': typeof RoadmapSharedTokenRoute
  '/project/roadmap': typeof ProjectRoadmapIndexRoute
  '/project/$projectId/roadmap/$roadmapId': typeof ProjectProjectIdRoadmapRoadmapIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/landing': typeof LandingRoute
  '/onboarding': typeof OnboardingRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/approve-admin': typeof AdminApproveAdminRoute
  '/admin/match': typeof AdminMatchRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/client/project-posting': typeof ClientProjectPostingRoute
  '/consultant/$profileId': typeof ConsultantProfileIdRoute
  '/consultant/apply': typeof ConsultantApplyRoute
  '/consultant/browse': typeof ConsultantBrowseRoute
  '/profile/$profileId': typeof ProfileProfileIdRoute
  '/project/$projectId': typeof ProjectProjectIdRouteWithChildren
  '/roadmap/shared-with-me': typeof RoadmapSharedWithMeRoute
  '/admin/': typeof AdminIndexRoute
  '/auth/admin/login': typeof AuthAdminLoginRoute
  '/auth/admin/signin': typeof AuthAdminSigninRoute
  '/project/$projectId/files': typeof ProjectProjectIdFilesRoute
  '/project/$projectId/overview': typeof ProjectProjectIdOverviewRoute
  '/project/$projectId/payments': typeof ProjectProjectIdPaymentsRoute
  '/project/$projectId/roadmap': typeof ProjectProjectIdRoadmapRouteWithChildren
  '/project/$projectId/time': typeof ProjectProjectIdTimeRoute
  '/project/$projectId/work-items': typeof ProjectProjectIdWorkItemsRoute
  '/roadmap/shared/$token': typeof RoadmapSharedTokenRoute
  '/project/roadmap/': typeof ProjectRoadmapIndexRoute
  '/project/$projectId/roadmap/$roadmapId': typeof ProjectProjectIdRoadmapRoadmapIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/landing'
    | '/onboarding'
    | '/admin/applications'
    | '/admin/approve-admin'
    | '/admin/match'
    | '/admin/settings'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/signup'
    | '/auth/verify'
    | '/client/project-posting'
    | '/consultant/$profileId'
    | '/consultant/apply'
    | '/consultant/browse'
    | '/profile/$profileId'
    | '/project/$projectId'
    | '/roadmap/shared-with-me'
    | '/admin/'
    | '/auth/admin/login'
    | '/auth/admin/signin'
    | '/project/$projectId/files'
    | '/project/$projectId/overview'
    | '/project/$projectId/payments'
    | '/project/$projectId/roadmap'
    | '/project/$projectId/time'
    | '/project/$projectId/work-items'
    | '/roadmap/shared/$token'
    | '/project/roadmap'
    | '/project/$projectId/roadmap/$roadmapId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/landing'
    | '/onboarding'
    | '/admin/applications'
    | '/admin/approve-admin'
    | '/admin/match'
    | '/admin/settings'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/signup'
    | '/auth/verify'
    | '/client/project-posting'
    | '/consultant/$profileId'
    | '/consultant/apply'
    | '/consultant/browse'
    | '/profile/$profileId'
    | '/project/$projectId'
    | '/roadmap/shared-with-me'
    | '/admin'
    | '/auth/admin/login'
    | '/auth/admin/signin'
    | '/project/$projectId/files'
    | '/project/$projectId/overview'
    | '/project/$projectId/payments'
    | '/project/$projectId/roadmap'
    | '/project/$projectId/time'
    | '/project/$projectId/work-items'
    | '/roadmap/shared/$token'
    | '/project/roadmap'
    | '/project/$projectId/roadmap/$roadmapId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/landing'
    | '/onboarding'
    | '/admin/applications'
    | '/admin/approve-admin'
    | '/admin/match'
    | '/admin/settings'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/signup'
    | '/auth/verify'
    | '/client/project-posting'
    | '/consultant/$profileId'
    | '/consultant/apply'
    | '/consultant/browse'
    | '/profile/$profileId'
    | '/project/$projectId'
    | '/roadmap/shared-with-me'
    | '/admin/'
    | '/auth/admin/login'
    | '/auth/admin/signin'
    | '/project/$projectId/files'
    | '/project/$projectId/overview'
    | '/project/$projectId/payments'
    | '/project/$projectId/roadmap'
    | '/project/$projectId/time'
    | '/project/$projectId/work-items'
    | '/roadmap/shared/$token'
    | '/project/roadmap/'
    | '/project/$projectId/roadmap/$roadmapId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  LandingRoute: typeof LandingRoute
  OnboardingRoute: typeof OnboardingRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
  ClientProjectPostingRoute: typeof ClientProjectPostingRoute
  ConsultantProfileIdRoute: typeof ConsultantProfileIdRoute
  ConsultantApplyRoute: typeof ConsultantApplyRoute
  ConsultantBrowseRoute: typeof ConsultantBrowseRoute
  ProfileProfileIdRoute: typeof ProfileProfileIdRoute
  ProjectProjectIdRoute: typeof ProjectProjectIdRouteWithChildren
  RoadmapSharedWithMeRoute: typeof RoadmapSharedWithMeRoute
  AuthAdminLoginRoute: typeof AuthAdminLoginRoute
  AuthAdminSigninRoute: typeof AuthAdminSigninRoute
  RoadmapSharedTokenRoute: typeof RoadmapSharedTokenRoute
  ProjectRoadmapIndexRoute: typeof ProjectRoadmapIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/roadmap/shared-with-me': {
      id: '/roadmap/shared-with-me'
      path: '/roadmap/shared-with-me'
      fullPath: '/roadmap/shared-with-me'
      preLoaderRoute: typeof RoadmapSharedWithMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$projectId': {
      id: '/project/$projectId'
      path: '/project/$projectId'
      fullPath: '/project/$projectId'
      preLoaderRoute: typeof ProjectProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$profileId': {
      id: '/profile/$profileId'
      path: '/profile/$profileId'
      fullPath: '/profile/$profileId'
      preLoaderRoute: typeof ProfileProfileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultant/browse': {
      id: '/consultant/browse'
      path: '/consultant/browse'
      fullPath: '/consultant/browse'
      preLoaderRoute: typeof ConsultantBrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultant/apply': {
      id: '/consultant/apply'
      path: '/consultant/apply'
      fullPath: '/consultant/apply'
      preLoaderRoute: typeof ConsultantApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultant/$profileId': {
      id: '/consultant/$profileId'
      path: '/consultant/$profileId'
      fullPath: '/consultant/$profileId'
      preLoaderRoute: typeof ConsultantProfileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/project-posting': {
      id: '/client/project-posting'
      path: '/client/project-posting'
      fullPath: '/client/project-posting'
      preLoaderRoute: typeof ClientProjectPostingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify': {
      id: '/auth/verify'
      path: '/auth/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/match': {
      id: '/admin/match'
      path: '/match'
      fullPath: '/admin/match'
      preLoaderRoute: typeof AdminMatchRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/approve-admin': {
      id: '/admin/approve-admin'
      path: '/approve-admin'
      fullPath: '/admin/approve-admin'
      preLoaderRoute: typeof AdminApproveAdminRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/applications': {
      id: '/admin/applications'
      path: '/applications'
      fullPath: '/admin/applications'
      preLoaderRoute: typeof AdminApplicationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/project/roadmap/': {
      id: '/project/roadmap/'
      path: '/project/roadmap'
      fullPath: '/project/roadmap'
      preLoaderRoute: typeof ProjectRoadmapIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap/shared/$token': {
      id: '/roadmap/shared/$token'
      path: '/roadmap/shared/$token'
      fullPath: '/roadmap/shared/$token'
      preLoaderRoute: typeof RoadmapSharedTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$projectId/work-items': {
      id: '/project/$projectId/work-items'
      path: '/work-items'
      fullPath: '/project/$projectId/work-items'
      preLoaderRoute: typeof ProjectProjectIdWorkItemsRouteImport
      parentRoute: typeof ProjectProjectIdRoute
    }
    '/project/$projectId/time': {
      id: '/project/$projectId/time'
      path: '/time'
      fullPath: '/project/$projectId/time'
      preLoaderRoute: typeof ProjectProjectIdTimeRouteImport
      parentRoute: typeof ProjectProjectIdRoute
    }
    '/project/$projectId/roadmap': {
      id: '/project/$projectId/roadmap'
      path: '/roadmap'
      fullPath: '/project/$projectId/roadmap'
      preLoaderRoute: typeof ProjectProjectIdRoadmapRouteImport
      parentRoute: typeof ProjectProjectIdRoute
    }
    '/project/$projectId/payments': {
      id: '/project/$projectId/payments'
      path: '/payments'
      fullPath: '/project/$projectId/payments'
      preLoaderRoute: typeof ProjectProjectIdPaymentsRouteImport
      parentRoute: typeof ProjectProjectIdRoute
    }
    '/project/$projectId/overview': {
      id: '/project/$projectId/overview'
      path: '/overview'
      fullPath: '/project/$projectId/overview'
      preLoaderRoute: typeof ProjectProjectIdOverviewRouteImport
      parentRoute: typeof ProjectProjectIdRoute
    }
    '/project/$projectId/files': {
      id: '/project/$projectId/files'
      path: '/files'
      fullPath: '/project/$projectId/files'
      preLoaderRoute: typeof ProjectProjectIdFilesRouteImport
      parentRoute: typeof ProjectProjectIdRoute
    }
    '/auth/admin/signin': {
      id: '/auth/admin/signin'
      path: '/auth/admin/signin'
      fullPath: '/auth/admin/signin'
      preLoaderRoute: typeof AuthAdminSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/admin/login': {
      id: '/auth/admin/login'
      path: '/auth/admin/login'
      fullPath: '/auth/admin/login'
      preLoaderRoute: typeof AuthAdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$projectId/roadmap/$roadmapId': {
      id: '/project/$projectId/roadmap/$roadmapId'
      path: '/$roadmapId'
      fullPath: '/project/$projectId/roadmap/$roadmapId'
      preLoaderRoute: typeof ProjectProjectIdRoadmapRoadmapIdRouteImport
      parentRoute: typeof ProjectProjectIdRoadmapRoute
    }
  }
}

interface AdminRouteChildren {
  AdminApplicationsRoute: typeof AdminApplicationsRoute
  AdminApproveAdminRoute: typeof AdminApproveAdminRoute
  AdminMatchRoute: typeof AdminMatchRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminApplicationsRoute: AdminApplicationsRoute,
  AdminApproveAdminRoute: AdminApproveAdminRoute,
  AdminMatchRoute: AdminMatchRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ProjectProjectIdRoadmapRouteChildren {
  ProjectProjectIdRoadmapRoadmapIdRoute: typeof ProjectProjectIdRoadmapRoadmapIdRoute
}

const ProjectProjectIdRoadmapRouteChildren: ProjectProjectIdRoadmapRouteChildren =
  {
    ProjectProjectIdRoadmapRoadmapIdRoute:
      ProjectProjectIdRoadmapRoadmapIdRoute,
  }

const ProjectProjectIdRoadmapRouteWithChildren =
  ProjectProjectIdRoadmapRoute._addFileChildren(
    ProjectProjectIdRoadmapRouteChildren,
  )

interface ProjectProjectIdRouteChildren {
  ProjectProjectIdFilesRoute: typeof ProjectProjectIdFilesRoute
  ProjectProjectIdOverviewRoute: typeof ProjectProjectIdOverviewRoute
  ProjectProjectIdPaymentsRoute: typeof ProjectProjectIdPaymentsRoute
  ProjectProjectIdRoadmapRoute: typeof ProjectProjectIdRoadmapRouteWithChildren
  ProjectProjectIdTimeRoute: typeof ProjectProjectIdTimeRoute
  ProjectProjectIdWorkItemsRoute: typeof ProjectProjectIdWorkItemsRoute
}

const ProjectProjectIdRouteChildren: ProjectProjectIdRouteChildren = {
  ProjectProjectIdFilesRoute: ProjectProjectIdFilesRoute,
  ProjectProjectIdOverviewRoute: ProjectProjectIdOverviewRoute,
  ProjectProjectIdPaymentsRoute: ProjectProjectIdPaymentsRoute,
  ProjectProjectIdRoadmapRoute: ProjectProjectIdRoadmapRouteWithChildren,
  ProjectProjectIdTimeRoute: ProjectProjectIdTimeRoute,
  ProjectProjectIdWorkItemsRoute: ProjectProjectIdWorkItemsRoute,
}

const ProjectProjectIdRouteWithChildren =
  ProjectProjectIdRoute._addFileChildren(ProjectProjectIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  DashboardRoute: DashboardRoute,
  LandingRoute: LandingRoute,
  OnboardingRoute: OnboardingRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthVerifyRoute: AuthVerifyRoute,
  ClientProjectPostingRoute: ClientProjectPostingRoute,
  ConsultantProfileIdRoute: ConsultantProfileIdRoute,
  ConsultantApplyRoute: ConsultantApplyRoute,
  ConsultantBrowseRoute: ConsultantBrowseRoute,
  ProfileProfileIdRoute: ProfileProfileIdRoute,
  ProjectProjectIdRoute: ProjectProjectIdRouteWithChildren,
  RoadmapSharedWithMeRoute: RoadmapSharedWithMeRoute,
  AuthAdminLoginRoute: AuthAdminLoginRoute,
  AuthAdminSigninRoute: AuthAdminSigninRoute,
  RoadmapSharedTokenRoute: RoadmapSharedTokenRoute,
  ProjectRoadmapIndexRoute: ProjectRoadmapIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
