-- =============================================================================
-- Migration: Comprehensive Languages Dataset
-- Created: 2026-02-26
-- Source:   ISO 639-1 language codes (official 2-letter codes)
--           Curated list of 184 living languages with significant speaker populations.
--           Reference: https://www.loc.gov/standards/iso639-2/php/code_list.php
--           Additional reference: https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes
-- =============================================================================

-- Truncate existing seed data (the 16-row seed from the initial migration)
-- and replace with the comprehensive set.
DELETE FROM public.user_languages;  -- remove any existing user_language rows first
TRUNCATE TABLE public.languages RESTART IDENTITY CASCADE;

INSERT INTO public.languages (code, name) VALUES
-- A ─────────────────────────────────────────────────────────────────────────
('aa', 'Afar'),
('ab', 'Abkhazian'),
('af', 'Afrikaans'),
('ak', 'Akan'),
('am', 'Amharic'),
('ar', 'Arabic'),
('an', 'Aragonese'),
('as', 'Assamese'),
('av', 'Avaric'),
('ay', 'Aymara'),
('az', 'Azerbaijani'),
-- B ─────────────────────────────────────────────────────────────────────────
('ba', 'Bashkir'),
('be', 'Belarusian'),
('bg', 'Bulgarian'),
('bh', 'Bihari languages'),
('bi', 'Bislama'),
('bm', 'Bambara'),
('bn', 'Bengali'),
('bo', 'Tibetan'),
('br', 'Breton'),
('bs', 'Bosnian'),
-- C ─────────────────────────────────────────────────────────────────────────
('ca', 'Catalan'),
('ce', 'Chechen'),
('ch', 'Chamorro'),
('co', 'Corsican'),
('cr', 'Cree'),
('cs', 'Czech'),
('cu', 'Church Slavic'),
('cv', 'Chuvash'),
('cy', 'Welsh'),
-- D ─────────────────────────────────────────────────────────────────────────
('da', 'Danish'),
('de', 'German'),
('dv', 'Divehi'),
('dz', 'Dzongkha'),
-- E ─────────────────────────────────────────────────────────────────────────
('ee', 'Ewe'),
('el', 'Greek'),
('en', 'English'),
('eo', 'Esperanto'),
('es', 'Spanish'),
('et', 'Estonian'),
('eu', 'Basque'),
-- F ─────────────────────────────────────────────────────────────────────────
('fa', 'Persian'),
('ff', 'Fulah'),
('fi', 'Finnish'),
('fj', 'Fijian'),
('fo', 'Faroese'),
('fr', 'French'),
('fy', 'Western Frisian'),
-- G ─────────────────────────────────────────────────────────────────────────
('ga', 'Irish'),
('gd', 'Scottish Gaelic'),
('gl', 'Galician'),
('gn', 'Guarani'),
('gu', 'Gujarati'),
('gv', 'Manx'),
-- H ─────────────────────────────────────────────────────────────────────────
('ha', 'Hausa'),
('he', 'Hebrew'),
('hi', 'Hindi'),
('ho', 'Hiri Motu'),
('hr', 'Croatian'),
('ht', 'Haitian Creole'),
('hu', 'Hungarian'),
('hy', 'Armenian'),
-- I ─────────────────────────────────────────────────────────────────────────
('hz', 'Herero'),
('ia', 'Interlingua'),
('id', 'Indonesian'),
('ie', 'Interlingue'),
('ig', 'Igbo'),
('ii', 'Sichuan Yi'),
('ik', 'Inupiaq'),
('io', 'Ido'),
('is', 'Icelandic'),
('it', 'Italian'),
('iu', 'Inuktitut'),
-- J ─────────────────────────────────────────────────────────────────────────
('ja', 'Japanese'),
('jv', 'Javanese'),
-- K ─────────────────────────────────────────────────────────────────────────
('ka', 'Georgian'),
('kg', 'Kongo'),
('ki', 'Kikuyu'),
('kj', 'Kwanyama'),
('kk', 'Kazakh'),
('kl', 'Kalaallisut'),
('km', 'Khmer'),
('kn', 'Kannada'),
('ko', 'Korean'),
('kr', 'Kanuri'),
('ks', 'Kashmiri'),
('ku', 'Kurdish'),
('kv', 'Komi'),
('kw', 'Cornish'),
('ky', 'Kyrgyz'),
-- L ─────────────────────────────────────────────────────────────────────────
('la', 'Latin'),
('lb', 'Luxembourgish'),
('lg', 'Ganda'),
('li', 'Limburgan'),
('ln', 'Lingala'),
('lo', 'Lao'),
('lt', 'Lithuanian'),
('lu', 'Luba-Katanga'),
('lv', 'Latvian'),
-- M ─────────────────────────────────────────────────────────────────────────
('mg', 'Malagasy'),
('mh', 'Marshallese'),
('mi', 'Maori'),
('mk', 'Macedonian'),
('ml', 'Malayalam'),
('mn', 'Mongolian'),
('mr', 'Marathi'),
('ms', 'Malay'),
('mt', 'Maltese'),
('my', 'Burmese'),
-- N ─────────────────────────────────────────────────────────────────────────
('na', 'Nauru'),
('nb', 'Norwegian Bokmål'),
('nd', 'North Ndebele'),
('ne', 'Nepali'),
('ng', 'Ndonga'),
('nl', 'Dutch'),
('nn', 'Norwegian Nynorsk'),
('no', 'Norwegian'),
('nr', 'South Ndebele'),
('nv', 'Navajo'),
('ny', 'Chichewa'),
-- O ─────────────────────────────────────────────────────────────────────────
('oc', 'Occitan'),
('oj', 'Ojibwe'),
('om', 'Oromo'),
('or', 'Odia'),
('os', 'Ossetic'),
-- P ─────────────────────────────────────────────────────────────────────────
('pa', 'Punjabi'),
('pi', 'Pali'),
('pl', 'Polish'),
('ps', 'Pashto'),
('pt', 'Portuguese'),
-- Q ─────────────────────────────────────────────────────────────────────────
('qu', 'Quechua'),
-- R ─────────────────────────────────────────────────────────────────────────
('rm', 'Romansh'),
('rn', 'Rundi'),
('ro', 'Romanian'),
('ru', 'Russian'),
('rw', 'Kinyarwanda'),
-- S ─────────────────────────────────────────────────────────────────────────
('sa', 'Sanskrit'),
('sc', 'Sardinian'),
('sd', 'Sindhi'),
('se', 'Northern Sami'),
('sg', 'Sango'),
('si', 'Sinhala'),
('sk', 'Slovak'),
('sl', 'Slovenian'),
('sm', 'Samoan'),
('sn', 'Shona'),
('so', 'Somali'),
('sq', 'Albanian'),
('sr', 'Serbian'),
('ss', 'Swati'),
('st', 'Southern Sotho'),
('su', 'Sundanese'),
('sv', 'Swedish'),
('sw', 'Swahili'),
-- T ─────────────────────────────────────────────────────────────────────────
('ta', 'Tamil'),
('te', 'Telugu'),
('tg', 'Tajik'),
('th', 'Thai'),
('ti', 'Tigrinya'),
('tk', 'Turkmen'),
('tl', 'Filipino'),
('tn', 'Tswana'),
('to', 'Tonga'),
('tr', 'Turkish'),
('ts', 'Tsonga'),
('tt', 'Tatar'),
('tw', 'Twi'),
('ty', 'Tahitian'),
-- U ─────────────────────────────────────────────────────────────────────────
('ug', 'Uyghur'),
('uk', 'Ukrainian'),
('ur', 'Urdu'),
('uz', 'Uzbek'),
-- V ─────────────────────────────────────────────────────────────────────────
('va', 'Valencian'),
('ve', 'Venda'),
('vi', 'Vietnamese'),
('vo', 'Volapuk'),
-- W ─────────────────────────────────────────────────────────────────────────
('wa', 'Walloon'),
('wo', 'Wolof'),
-- X ─────────────────────────────────────────────────────────────────────────
('xh', 'Xhosa'),
-- Y ─────────────────────────────────────────────────────────────────────────
('yi', 'Yiddish'),
('yo', 'Yoruba'),
-- Z ─────────────────────────────────────────────────────────────────────────
('za', 'Zhuang'),
('zh', 'Chinese'),
('zu', 'Zulu')
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name;
